RSS_FEEDS = [
    "https://blog.langchain.dev/rss/",
    "https://www.reddit.com/r/LanguageTechnology",
    "https://news.mit.edu/topic/mitmachine-learning-rss.xml",
    "https://www.reddit.com/r/neuralnetworks",
    "https://bair.berkeley.edu/blog/feed.xml",
    "https://topenddevs.com/podcasts/adventures-in-machine-learning/rss.rss",
    "https://stackoverflow.blog/feed/",
    "https://openai.com/blog/rss.xml",
    "https://www.blog.pythonlibrary.org/feed/",
    "https://javascriptweekly.com/rss",
    "https://www.fastapi.tiangolo.com/feed.xml",
    "https://huggingface.co/blog/feed.xml",
    "https://feeds.feedburner.com/TheHackersNews",
    "https://feeds.acast.com/public/shows/e421d786-ec36-4148-aa99-7a3b2928a779",
]
